#!/usr/bin/env php
<?php



require_once(__DIR__ . '/../vendor/autoload.php'); // Подключение автозагрузки Composer

use function cli\line;
use function cli\prompt;
use function BrainGames\even\getName;
use function BrainGames\even\playEvenGame;


$name = getName();
playEvenGame($name);

